import Head from 'next/head'
import Contato from '../components/Contato'
import Main from '../components/main'
import Servicos from '../components/Servicos/Servicos'
import SobreMin from '../components/SobreMIn'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vinicius José </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/image/favicon.png" type="image/x-icon" />
      </Head>
      <Main />
      <Servicos />
      <SobreMin />
      <Contato />

    </div>
  )
}
